### ISSUE TITLE
typings

### ISSUE THREAD

**Issue by danimality** [johnedvard/typescript-angular-node-express-template#1]
Good work with this by the way, just a quick(?) question - how would you modify this for use with typings?

thanks

**Comment by johnedvard** [comment]
Thank you for the comment. I was actually just copying the code from this [blog](http://blog.edenmsg.com/angular2-typescript-gulp-and-expressjs/), and you might get some extra help from that blog as well. 
I am not sure what you mean by modifying this for use with typings. Do you have an example?
