### ISSUE TITLE
'require is not defined' error  in client code.

### ISSUE THREAD

**Issue by 29er** [johnedvard/typescript-angular-node-express-template#2]
I remember you were having issues with 'require' not being defined from Maximillan's github, but I am still getting the 'require' errors.

for example, if I try to bring in an external template, I get Error : require is not defined ( from angular2-polyfills.js138)  Can you help ??

**About.ts**

```
import {Component} from 'angular2/core'

 @Component({
     template: require('about.html'),
     selector: 'home'
 })
 export class AboutComponent{
     titleName: string;
     constructor(){
         this.titleName = "Hello from About"
     }

 }
```

Thanks!

**Comment by johnedvard** [comment]
Is the error from `template: require('about.html')` inside the @Component? 
It looks like you should use `templateUrl: "about.html"` instead, and put it inside the @View like this:

```
import {Component} from 'angular2/core'

 @Component({
     selector: 'home'
 })

@View({
    templateUrl:'about.html'
})

 export class AboutComponent{
     titleName: string;
     constructor(){
         this.titleName = "Hello from About"
     }

 }
```
